;; There is a bug in GNU Emacs 25.3
;; See discussion here: https://github.com/cask/cask/issues/373#issuecomment-359774251
;; Add the following to /usr/local/Cellar/cask/0.8.1_1/cask-cli.el
;;
;;   (require 'gnutls)
;;   (add-to-list 'gnutls-trustfiles "/private/etc/ssl/cert.pem")

(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "helm")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "textmate")
(depends-on "multi-term")
(depends-on "exec-path-from-shell")
(depends-on "powerline")
(depends-on "cider") ;; CIDER extends Emacs with support for interactive programming in Clojure
(depends-on "slim-mode")
(depends-on "fzf")
(depends-on "rspec-mode")
(depends-on "rbenv")
(depends-on "coffee-mode")
(depends-on "markdown-mode")
(depends-on "go-mode")
